targets:
  $default:
    builders:
      freezed:freezed:
        generate_for:
          include:
            - lib/data/models/**.dart
            - lib/data/models/**/**.dart
            - lib/data/source/**/**.dart
            - lib/controllers/**/**.dart
      json_serializable:
        generate_for:
          include:
            - lib/data/models/**.dart
            - lib/data/models/**/**.dart
            - lib/data/source/**/**.dart
            - lib/controllers/**/**.dart
        options:
          explicit_to_json: true
          include_if_null: false