name: app
description: A new Flutter project.
publish_to: 'none'
version: 1.9.1+39

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  animated_icon_button: ^1.0.2
  assorted_layout_widgets: ^8.0.5
  awesome_notifications: ^0.6.19
  cloud_firestore: ^4.12.2
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  downloads_path_provider_28: ^0.1.2
  easy_localization: ^3.0.1
  file_picker: ^5.2.2
  firebase_core: ^2.21.0
  firebase_messaging: ^14.7.3
  flutter_app_badger: ^1.5.0
  flutter_bloc: ^8.1.3
  flutter_feather_icons: ^2.0.0+1
  flutter_local_notifications: ^13.0.0
  freezed_annotation: ^2.2.0
  get: ^4.6.5
  geocoding: ^2.0.5
  geolocator: ^9.0.1
  get_it: ^7.6.4
  get_storage: ^2.1.1
  google_maps_flutter: ^2.2.1
  hooks_riverpod: ^2.1.1
  http: ^0.13.5
  hydrated_bloc: ^9.1.2
  image: ^4.1.3
  image_picker: ^0.8.6
  in_app_review: ^2.0.8
  intl: ^0.18.0
  json_annotation: ^4.6.0
  open_file_plus: ^3.4.1
  path_provider: ^2.0.15
  permission_handler: ^10.2.0
  pretty_dio_logger: ^1.2.0-beta-1
  retrofit: ^3.0.1+1
  shared_preferences: ^2.1.1
  sliding_up_panel: ^2.0.0+1
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.1.11
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  built_value_generator: ^8.4.0
  flutter_lints: ^2.0.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  retrofit_generator: ^4.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/logo/
    - assets/icons/tutorial/
    - assets/lang/
    - assets/google_fonts/
    - images/map-pin-gif.gif
    - images/check-gif.gif
    - images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/google_fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/google_fonts/Montserrat-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/google_fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/google_fonts/Montserrat-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/google_fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/google_fonts/Montserrat-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/google_fonts/Montserrat-Regular.ttf
        - asset: assets/google_fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/google_fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/google_fonts/Montserrat-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/google_fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/google_fonts/Montserrat-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/google_fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/google_fonts/Montserrat-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/google_fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/google_fonts/Montserrat-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/google_fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/google_fonts/Montserrat-BlackItalic.ttf
          style: italic
          weight: 900